### ISSUE TITLE
ios9 seems have problems

### ISSUE THREAD

**Issue by ivangodfather** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#106]
I have a UILabel inside the parallaxHeader with number of lines = 0.
I have no outlets, and nothing about it, and i set the height of the parallax to 300
```
     override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        if let layout = collectionView?.collectionViewLayout as? CSStickyHeaderFlowLayout {
            layout.parallaxHeaderReferenceSize = CGSizeMake(collectionView!.frame.size.width, 300)
           .. 
     }
```

And this is how it looks like the xib im using:
![screen shot 2015-10-01 at 09 43 21](https://cloud.githubusercontent.com/assets/1838117/10215365/24158c74-6821-11e5-8ad9-2642d745b770.png)

And this is how i see it on ios8 (which is fine cause dont get cut off):
![screen shot 2015-10-01 at 09 44 58](https://cloud.githubusercontent.com/assets/1838117/10215369/31c0c0c8-6821-11e5-8ca2-72a4a7ef46ef.png)

**Comment by ivangodfather** [comment]
Its wierd, i tested in your github projects and it happens the opposite, on ios9 it works as expected and on ios 8 the label gets cut off

![screen shot 2015-10-01 at 09 59 30](https://cloud.githubusercontent.com/assets/1838117/10215664/dd651b8e-6823-11e5-8ef1-ed1001a38126.png)

**Comment by jamztang** [comment]
how about setting the `preferredMaxLayoutWidth` of the `UILabel`?

**Comment by ivangodfather** [comment]
it worked, but... why?

**Comment by jamztang** [comment]
I am not the best person to explain this but it seemed like to be a technical requirement. There's a thread on Stackoverflow discussed this. http://stackoverflow.com/questions/17491376/ios-autolayout-multi-line-uilabel
