### ISSUE TITLE
problem with sticky header

### ISSUE THREAD

**Issue by getacopio** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#108]
hi i have a problem with  always top view like this : 
http://uupload.ir/files/dmxd_screen_shot_2015-10-14_at_8.53.57_pm.png

can you say me how can i prevent this issue ?

**Comment by jamztang** [comment]
Try adjusting contentInset.top?

**Comment by mfarhand** [comment]
yes but it's not work

**Comment by jamztang** [comment]
Yes, you may have to turn off autoAdjustContentInset property for collection view as well.

**Comment by mfarhand** [comment]
thank you , i will check it and notify you :)

**Comment by callmebill** [comment]
I have the same problem . After checking. I found layoutAttributes calculate is ok.Anything is ok. Just UICollectionReusableView applylayoutattributes can't be call. But I don't no the reason.I need the answer really。
