### ISSUE TITLE
has no segue with identifier for swift 2

### ISSUE THREAD

**Issue by deter3** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#111]
using github swift demo , trying to click one cell to segue to another view , double confirmed has the segue identifier between two views in the storyboard , but 

    override func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
        self.performSegueWithIdentifier("showphotos", sender: self)
    }

the app crashed with " Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Receiver (<SwiftDemo.CollectionViewController: 0x7fadf0637ed0>) has no segue with identifier 'showphotos'' .  I checked storyboard  , the segue is between two view controllers level , not cell link to view controller . 

Instead using "presentViewController(nextViewController, animated: true, completion: nil)" is working . 

why there's no segue with identifier ?  Anybody has ideas of how to fix it ? 

p.s. I test object-c version , no problem .

**Comment by jamztang** [comment]
Do you think it's an issue particularly to this library or something else? Maybe you can try not to use CSStickyHeaderFlowLayout and see if same thing happens in Swift 2.0?

**Comment by deter3** [comment]
object-c demo has no such issue and swift 2.0 demo has the issue . I think it's CSStickyHeaderFlowLayout swift demo code issue .

**Comment by deter3** [comment]
what I have done : 

1.  tested object-c demo code in CSStickyHeaderFlowLayout repository  , result : segue is working 
2. tested swift demo code in  CSStickyHeaderFlowLayout repository , result : segue is not working 
3. tested swift code in https://github.com/KevinAyuque/WWDC-2015-Scholarship , who is using CSStickyHeaderFlowLayout as only library , result : segue is working 

I think the swift demo code in CSStickyHeaderFlowLayout repository need to be revised to get ride of 

1. segue issues 
2. tar bar is not able to show up issues

**Comment by deter3** [comment]
I found out the solution to swift demo code no segue . 

1. just remove the code above from appdelegate.app .
2. make sure layout class is CSStickyHeaderFlowLayout as below . 


![f6e421e1-da40-4c5b-a44f-47ea2954a175](https://cloud.githubusercontent.com/assets/11637246/10786572/496e6818-7dae-11e5-9de8-a0fbc1b4ace7.png)
![32bf7e61-9cce-4853-94c6-40658a6558bd](https://cloud.githubusercontent.com/assets/11637246/10786577/4cf74374-7dae-11e5-989d-8a3fd20d71ee.png)
