### ISSUE TITLE
How to implement without section headers

### ISSUE THREAD

**Issue by Neil3079** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#118]
My design requires a parralax header but then no section header before my content, even when i set the layout header reference size to zero it still looks to deque a UICollectionElementKindSectionHeader?

**Comment by tolgaarikan** [comment]
Well it is probably too late for you to take advantage of this answer but I will answer anyway for future reference 


        let stickyFlow = CSStickyHeaderFlowLayout()

        stickyFlow.disableStickyHeaders = true
        
        self.collectionView?.collectionViewLayout = stickyFlow

Basically you can disable it with `disableStickyHeaders = true`
