### ISSUE TITLE
framework not found CSStickyHeaderFlowLayout

### ISSUE THREAD

**Issue by mrjcka** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#120]
Thank for the wonderful plugin, I was trying to implementing it and found
"ld: framework not found CSStickyHeaderFlowLayout
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

I do open with xcodespace project, and using https://gist.github.com/acrookston/c47c4131adb462d0ddf7 for my swift code, all just fine until I tried to built it

Any help would be appriciate!

**Comment by sentiasa** [comment]
I have the same problem. Did you manage to solve it eventually?

**Comment by chrene** [comment]
Did you open your project.xcodeproject or project.xcworkspace?
