### ISSUE TITLE
Header Section animating while using reloadSections

### ISSUE THREAD

**Issue by vivekshah05** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#127]
I have requirement in which I have to reload particular section instead of whole collectionView.
Now when I scroll collectionView and then try to reload that section, the header section comes with top to down animation. Can you pls help me ?

[CollectionView reloadSections:[NSIndexSet indexSetWithIndex:sender.tag]]

**Comment by tylerjames** [comment]
I'm getting this same problem. It's not exactly critical but it's definitely annoying.

Did you happen to find any resolution?

**Comment by vivekshah05** [comment]
@tylerjames sorry but I didn't find any solution for that.

**Comment by chrene** [comment]
Can you try to wrap it in a `UIView.performWithoutAnimation(`
