### ISSUE TITLE
Request: Carthage support

### ISSUE THREAD

**Issue by thbaja** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#128]
Support for Carthage would be awesome :)

**Comment by Roylee-ML** [comment]
[RLStickyHeaderFlowLayout](https://github.com/Roylee-ML/RLStickyHeaderFlowLayout) this is a swift version for CSStickyHeaderFlowLayout, and it is Carthage support

**Comment by chrene** [comment]
I'm doing a PR in a couple of mins.

**Comment by chrene** [comment]
you can use chartage now. 
add this to your `Cartfile`
`github "CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout"`
