### ISSUE TITLE
when i pull down the header ,the image was stretched ,but i means that the image can stay the original height

### ISSUE THREAD

**Issue by 1966767119** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#129]
my code
`self.headerImg = [UIImageView new];
    self.headerImg.image = [UIImage imageNamed:@"tongly01"];
    self.headerImg.clipsToBounds = YES;
    [self addSubview:self.headerImg];
    self.headerImg.contentMode = UIViewContentModeScaleAspectFill;
    [self.headerImg mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.offset(12);
        make.right.offset(-12);
        make.top.offset(0);
        make.bottom.offset(0);
    }];`

**Comment by chrene** [comment]
`layout.disableStretching = YES;`
