### ISSUE TITLE
Warning once only: Detected a case where constraints ambiguously suggest a size of zero for a collection view cell's content view. We're considering the collapse unintentional and using standard size instead.

### ISSUE THREAD

**Issue by Mazorati** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#130]
I use MapKit in my Sticky HeaderFlowLayout. Few custom code. All from library. ios 8.4 +

**Comment by chrene** [comment]
How do you add your Map View? And what does your constraints look like. It could be possible that you need to be _very_ specific with your constraints. Try for instance to make an explicit constraint on the width. Also always remember to add views to the contentView of the cell and never on the cell itself.
