### ISSUE TITLE
Is it possible to implement this using Swift and the StoryBoard ?

### ISSUE THREAD

**Issue by HarishHary** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#131]
So as the subject of this thread says, i am trying to implement this using swift and the storyboard. I am have hard time using it. And I am kinda new to swift too. I really need help. If you guys have an example of implementation using this, with 2 different section and 2 different cell, it would be awesome !

Regards,

Hary.

**Comment by chrene** [comment]
I think you should watch some youtube videos for beginners. When you feel comfortable with UICollectionView and UICollectionViewLayout you will find that what you seek is a matter of changing a class in your storyboard.
