### ISSUE TITLE
Can't implement Always On Top example using swift

### ISSUE THREAD

**Issue by marcosMorales** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#133]
I'm trying to implement this case using Swift:
https://camo.githubusercontent.com/3aab9bc8e28dcde1a0fcd92eeac9d5ccf2507368/687474703a2f2f662e636c2e6c792f6974656d732f30353133307332723058316a3178314e3051336e2f73706f746966792d34382d31362d68616c662e676966
But these parameters seems to do nothing: parallaxHeaderAlwaysOnTop, disableStickyHeaders. Any ideas to solve it?

**Comment by Roylee-ML** [comment]
[RLStickyHeaderFlowLayout](https://github.com/Roylee-ML/RLStickyHeaderFlowLayout) this is a swift version for CSStickyHeaderFlowLayout, maybe it's helpfull for you.
