### ISSUE TITLE
Can I use this plug-in with PSTCollectionView?

### ISSUE THREAD

**Issue by hsol** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#140]
Can I use this plug-in with PSTCollectionView?

**Comment by chrene** [comment]
That should be possible. I don't know of `PSTCollectionView`, but `CSStickyHeaderFlowLayout` is simply a layout object for `UICollectionView`. So if `PSTCollectionView` can use a `UICollectionViewLayout` object then probably yes.
