### ISSUE TITLE
Is there a away to implement the header flow not using the nib files

### ISSUE THREAD

**Issue by yoshiboarder** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#141]
Hi I'm using the swift. It really awesome library.

I have a question.

Can I fix my header's height? When I scroll down then my header is always stretching...it affect my view's layout.

Is there a way to prevent this?

And Anyone know about get the frame.height of the header cell?

Here is my code.

```
if let layout = self.collectionViewLayout as? CSStickyHeaderFlowLayout {
            layout.parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.size.width, 216)

            layout.parallaxHeaderMinimumReferenceSize = CGSizeMake(self.view.frame.size.width, 216)
            layout.parallaxHeaderAlwaysOnTop = false
        }
```

**Comment by chrene** [comment]
Did you try `layout.disableStretching = true`?
