### ISSUE TITLE
How can i set transparent navigation bar for parallax header? 

### ISSUE THREAD

**Issue by vitali36** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#152]
I have a problem. I set transparent navigation bar, but for parallax header it doesn't working. But when i scroll my collectionView (section headers and cells) to the top, then navigation bar become transparent. 
If i set clipToBounds = false, then it's all ok, transparent worked, but  i have problems with layout when scrolling

**Comment by chrene** [comment]
sorry, I don't understand your question. Please provide a sample project or at least some code that can help us reproduce the issue. I'm not certain if this is a bug you are suggesting or something else.
