### ISSUE TITLE
How to define different itemSize for each cell?

### ISSUE THREAD

**Issue by burakkilic** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#157]
Hi;

I need to define different row heights in the collection view. But I couldn't do that. What is the proper way? 

My code is:

    - (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
    CollectionViewCell  *cell = [collectionView dequeueReusableCellWithReuseIdentifier:reuseIdentifier forIndexPath:indexPath];
    
    cell.textLabel.text = @"Chicken Quesadilla";
    CSStickyHeaderFlowLayout *layout = (id)self.collectionViewLayout;
    layout.itemSize = CGSizeMake(self.view.frame.size.width, indexPath.row * 10);
     return cell;
}

**Comment by chrene** [comment]
This question belongs on stackoverflow and I don't think it is related to CSStickyHeaderFlowLayout.

**Comment by AllLuckly** [comment]
@burakkilic 用这个框架继承 CHTCollectionViewWaterfallLayout 完美解决
