### ISSUE TITLE
Crash on iOS8 with auto sizing cells enabled.

### ISSUE THREAD

**Issue by jurajantas** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#48]
When auto sizing cells is enabled via setting estimated size
layout.estimatedItemSize = CGSizeMake(self.view.bounds.size.width, 80);
there is a crash in `- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect` method.

``` objective-c
- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect
{
    // The rect should compensate the header size
    CGRect adjustedRect = rect;
    adjustedRect.origin.y -= self.parallaxHeaderReferenceSize.height;

    NSMutableArray *allItems = [[super layoutAttributesForElementsInRect:adjustedRect] mutableCopy]; <-crash here 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
...
}
```
Didn't found remedy for it yet. Auto sizing is important feature, takes a lot of pain away. Would be cool if this was solved somehow.

**Comment by jamztang** [comment]
I did a quick play, it seems like sectionHeader wasn't playing nice with `UICollectionViewFlowLayout`. Once I remove sectionHeader from Storyboard, it doesn't crash. This is not particularly to `CSStickyHeaderFlowLayout` but to basic `UICollectionViewFlowLayout`

There's a thread from [StackoverFlow](
http://stackoverflow.com/questions/25460323/why-does-using-headerreferencesize-with-self-sizing-cells-in-a-collection-view-c) talking about the same issue. It's good if we can get some more help here.

**Comment by lexrus** [comment]
I'm facing the same issue.
Any updates?

**Comment by jurajantas** [comment]
Well, just dont use autosizing cells in collection views. It is broken. Unless Apple fix the problems you have to forget about auto sizing cells in collection views or switch to table views.

**Comment by chrene** [comment]
is this still an issue? I mean, auto sizing cells in collection views is terribly difficult to master. But did iOS 9 fix this problem? or will iOS 10 maybe?

**Comment by esetnik** [comment]
@chrene I was unable to get auto-sizing cells to work on iOS 9. There were layout issues as well as random crashes so I gave up and just calculated the dynamic cell sizes manually. I have not yet tried on iOS 10 but since most applications require support for iOS 9 I think UICollectionView with auto-sizing cells will not be usable for quite some time.

**Comment by chrene** [comment]
The only way I have managed to get them working is by really and I mean really being specific with the constraints. For instance if you have a table view style collection view, then install a constraint the specifically tells the layout the exact width of the items. For instance 320 or just the screen width. In that way I got it to work, but as always with autolayout it kills performance.
