### ISSUE TITLE
IndexPath is always coming Zero

### ISSUE THREAD

**Issue by kamabhavik** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#73]
We have imlemented this Sticky header flow layout in our applicaiton and we are having issues at
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath 
as we always getting IndexPath.row = 0.
So please let us know where we having the issue.

**Comment by jamztang** [comment]
Make sure to provide conditional logic according to the `kind` property.

**Comment by sumitjain7** [comment]
getting the same issue for iOS7 only

**Comment by jamztang** [comment]
Would you provide a bit more info on the code and output? As provided in the library, we have the CSStickyParallaxHeader and the original UICollectionElementHeader, we have to be sure which you're talking about

**Comment by sumitjain7** [comment]
import UIKit

class ProfileViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, ProfileHeaderDelegate, ServiceAdapterDelegate, ProfileSectionHeaderDelegate,CategoryListSelectionDelegate {

    var appDelegate:AppDelegateSwift = UIApplication.sharedApplication().delegate as! AppDelegateSwift;
    
    //------IBOUTLETS---------
    @IBOutlet weak var collectionView:UICollectionView!;
    
    @IBOutlet weak var categoryList: UIView!;
    @IBOutlet weak var categoryListTopConstraint: NSLayoutConstraint!
    
    @IBOutlet weak var navButton:UIButton!;
    var categoryListController:CategoryListViewController!;
    
    
    //----------- Variables-------
    
    var minTopYCategoryList:CGFloat = 0.0;
    
    var selectedIndex:Int!;
    
    var headerNib:UINib!;
    var myStatsArray:NSArray!;
    var myVotesArray:NSArray!;
    
    var activeDataSource:NSArray = NSArray();
    
    var activeMode:ProfileSectionHeader.ProfileModes = ProfileSectionHeader.ProfileModes.MY_STATS{
        didSet{
            if(activeMode == ProfileSectionHeader.ProfileModes.MY_STATS)
            {
                activeDataSource = myStatsArray;
               
            }
            else if(activeMode == ProfileSectionHeader.ProfileModes.MY_VOTES)
            {
                activeDataSource = myVotesArray;
            }
           
            self.collectionView.dataSource = nil;
            self.collectionView.dataSource = self;
            
//            collectionView.performBatchUpdates({ () -> Void in
//                self.collectionView.reloadData();
//                }, completion: nil)
            reloadLayout();
        }
    }
    
    required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder);
        
    }
    
    override func loadView() {
        super.loadView();
        
        
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.automaticallyAdjustsScrollViewInsets = false;
        self.minTopYCategoryList = -(self.view.frame.height - 64.0);
        
        categoryListTopConstraint.constant = minTopYCategoryList;
   //     collectionView.delegate = self;
    //    collectionView.dataSource = self;
        self.reloadLayout();
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), { () -> Void in
            self.reloadLayout();
            self.headerNib = UINib(nibName: "ProfileHeader", bundle: nil);
            self.collectionView.registerNib(self.headerNib, forSupplementaryViewOfKind: CSStickyHeaderParallaxHeader, withReuseIdentifier: "header");
        })
        
       
        
        setTheme();
        
    }
    
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated);
        
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), { () -> Void in
           if((self.myStatsArray == nil) || (self.myVotesArray == nil))
           {
                self.initiateWebService();
            }
        })
    }
    
    
    
    private func setTheme()
    {
        self.view.backgroundColor = UIColor(string: appDelegate.defaultCategory.categoryColorCode);
    }
    
    
    @IBAction func initiateSideBarNavigator(sender:UIButton)->Void
    {
        if(categoryListController == nil)
        {
            categoryListController = self.storyboard?.instantiateViewControllerWithIdentifier("categoryListController") as! CategoryListViewController;
            categoryListController.delegate = self;
            addChildViewController(categoryListController);
            categoryListController.view.frame = categoryList.bounds;
            categoryList.addSubview(categoryListController.view);
            categoryListController.didMoveToParentViewController(self);
            categoryListController.beginAppearanceTransition(true, animated: true);
            
            UIView.animateWithDuration(0.6, animations: { () -> Void in
                sender.transform = CGAffineTransformMakeRotation(CGFloat((90.0*M_PI)/180.0));
               
                self.categoryListTopConstraint.constant = 0;
                self.view.layoutIfNeeded();
     //           self.categoryListView.frame.origin.y = 64;
                //  self.categoryListView.layoutIfNeeded();
            })
        }
        else
        {
            removeCategoryListControl();
        }
        
    }
    
    private func removeCategoryListControl()->Void
    {
        if(categoryListController != nil)
        {
            UIView.animateWithDuration(0.6, animations: { () -> Void in
                self.navButton.transform = CGAffineTransformMakeRotation(CGFloat((0.0*M_PI)/180.0));
                self.categoryListTopConstraint.constant = self.minTopYCategoryList;
                self.view.layoutIfNeeded();
            //    self.categoryListView.frame.origin.y = -(self.view.frame.height - 64 - 64);
                }) { (Bool) -> Void in
                    self.categoryListController.view.removeFromSuperview();
                    self.categoryListController.removeFromParentViewController();
                    self.categoryListController.delegate = nil;
                    self.categoryListController = nil;
            }
        }
    }
    
    //--------------------------------------
    
    private func activateRandomCategory()->Void
    {
        var randomNum:Int = Int(arc4random_uniform(UInt32(appDelegate.vsCategories.count)));
        categorySelectionSuccessfull(appDelegate.vsCategories[randomNum]);
    }
    
    func closeCategoryListController() {
        removeCategoryListControl();
    }
    
    func categorySelectionSuccessfull(selectedCategory: CategoryVO) {
        appDelegate.defaultCategory = selectedCategory;
        setTheme();
        self.collectionView.reloadData();
        removeCategoryListControl();
        NSNotificationCenter.defaultCenter().postNotificationName(LocalNotifications.DEFAULT_CATEGORY_CHANGED, object: nil);
    }
    
    func shuffleSwitchUpdated(isShuffleEnabled: Bool) {
        if(isShuffleEnabled == true)
        {
            activateRandomCategory();
        }
    }
    
    //-------------------------------------
    private func initiateWebService()
    {
        var myStatsService:ServiceAdapter = ServiceAdapter();
        myStatsService.delegate = self;
        myStatsService.initiatePostRequest("{}", requestName: ServiceRequest.GET_MY_STATS, authNeeded: true);
        
        var myVotesService:ServiceAdapter = ServiceAdapter();
        myVotesService.delegate = self;
        myVotesService.initiatePostRequest("{}", requestName: ServiceRequest.GET_MY_VOTES, authNeeded: true);
    }
    
    
    private func reloadLayout()
    {
      //  var layout:CSStickyHeaderFlowLayout =
        (collectionView.collectionViewLayout as! CSStickyHeaderFlowLayout).parallaxHeaderReferenceSize = CGSizeMake(self.view.frame.width, 126);
//
      //  var layout:CSStickyHeaderFlowLayout = collectionView.collectionViewLayout;
       
        (collectionView.collectionViewLayout as! CSStickyHeaderFlowLayout).parallaxHeaderMinimumReferenceSize = CGSizeMake(self.view.frame.width, 126);
        
    }
    
    func numberOfSectionsInCollectionView(collectionView: UICollectionView) -> Int {
        return 1;
    }
    
    func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
    
//        if let dataSource = activeDataSource{
//            return dataSource.count;
//        }
//        else
//        {
//             return 0;
//        }
        return activeDataSource.count;
    }
    
    func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        var cell = collectionView.dequeueReusableCellWithReuseIdentifier("cell", forIndexPath: indexPath) as! StatsVotesCell;
       
        cell.data = activeDataSource.objectAtIndex(indexPath.item) as! NSDictionary;
        cell.mode = activeMode;
        
        var cellLayer = CALayer();
        cellLayer.frame = CGRectMake(-2.0, -2.0, (cell.frame.width + 4), (cell.frame.height + 4));
        cellLayer.borderWidth = 2;
        cellLayer.borderColor = UIColor(string: appDelegate.defaultCategory.categoryColorCode).CGColor;// UIColor(red: 1.0, green: 0.0, blue: 0.0, alpha: 1.0).CGColor;
        cell.layer.addSublayer(cellLayer);
        cell.clipsToBounds = false;
        cell.layer.masksToBounds = false;
        
        return cell;
    }
    
    func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        return CGSizeMake((collectionView.frame.width/2 - 1.0), (collectionView.frame.width/2));
    }
    
    func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView {
        
        var cell:UICollectionReusableView!;
        if(kind == CSStickyHeaderParallaxHeader)
        {
            cell = collectionView.dequeueReusableSupplementaryViewOfKind(kind, withReuseIdentifier: "header", forIndexPath: indexPath) as! ProfileHeader;
            (cell as! ProfileHeader).delegate = self;
        }
        else if(kind == UICollectionElementKindSectionHeader)
        {
            println("active data source ount : \(activeDataSource.count), \(indexPath.item)");
            cell = collectionView.dequeueReusableSupplementaryViewOfKind(kind, withReuseIdentifier: "sectionHeader", forIndexPath: indexPath) as! UICollectionReusableView;
            (cell as! ProfileSectionHeader).delegate = self;
            (cell as! ProfileSectionHeader).thumbView.backgroundColor = self.view.backgroundColor;
            (cell as! ProfileSectionHeader).myStatsButton.setTitleColor(self.view.backgroundColor, forState: UIControlState.Selected);
            (cell as! ProfileSectionHeader).myVotesBtn.setTitleColor(self.view.backgroundColor, forState: UIControlState.Selected);
            return cell;
        }
        return cell;
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func settingsButtonTapped() {
        dispatch_async(dispatch_get_main_queue()){
        self.performSegueWithIdentifier("openSettingsSegue", sender: self);
        }
    }
    
    func profileSectionModeUpdated(mode: ProfileSectionHeader.ProfileModes) {
       if(mode != self.activeMode)
       {
            activeMode = mode;
        }
    }
    
    
    func collectionView(collectionView: UICollectionView, didSelectItemAtIndexPath indexPath: NSIndexPath) {
        self.selectedIndex = indexPath.item;
        self.performSegueWithIdentifier("pairDetailSegue", sender: self);
    }
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if(segue.identifier == "pairDetailSegue")
        {
            var vc = segue.destinationViewController as! PairDetailViewController;
            vc.rawData = self.activeDataSource[self.selectedIndex] as! NSDictionary;
            println(self.activeDataSource[self.selectedIndex]);
        }
    }
    
    //------- SERVICE ADAPTER DELEGATE CONFIRMATION -----------
    
    func serviceAdapterResponse(responseVO: ResponseVO) {
        if(responseVO.status == responseVO.SUCCESS)
        {
            if(responseVO.requestName == ServiceRequest.GET_MY_STATS)
            {
                validateMyStatsResponseData(responseVO.data);
            }
            else if(responseVO.requestName == ServiceRequest.GET_MY_VOTES)
            {
                validateMyVotesResponseData(responseVO.data);
            }
        }
        else
        {
            // error message;
        }
    }
    
    private func validateMyStatsResponseData(responseData:NSDictionary)
    {
        self.collectionView.dataSource = nil;
        self.collectionView.delegate = nil;
        var status = responseData["status"] as? String;
        if(status == "success")
        {
            var pairs = responseData["data"] as! NSArray;
            self.myStatsArray = pairs;
            self.activeDataSource = myStatsArray;
           
            self.collectionView.dataSource = self;
            self.collectionView.delegate = self;
//            dispatch_async(dispatch_get_main_queue()){
//            
//                self.collectionView.performBatchUpdates({ () -> Void in
//                    
//                    indexSet.enumerateIndexesUsingBlock({ (idx, stop) -> Void in
//                        self.collectionView.insertItemsAtIndexPaths([NSIndexPath(forItem: idx, inSection: 0)]);
//                    })
//                    
//                    
//                }, completion: nil)
//            }
        }
        else
        {
            // error message;
        }
    }
    
    
    private func validateMyVotesResponseData(responseData:NSDictionary)
    {
        var status = responseData["status"] as? String;
        if(status == "success")
        {
            var pairs = responseData["data"] as! NSArray;
            self.myVotesArray = pairs;
            
        }
        else
        {
            // error message;
        }
    }
    
    //----IBACTION-----
    
    @IBAction func backButtonTapped(sender:UIButton)->Void
    {
        self.navigationController?.popViewControllerAnimated(true);
    }

}

**Comment by jamztang** [comment]
Hi @sumitjain7, I've wrapped your comment into code block to better format.

However, there seems to have a lot of external dependancies in your code, it'd be hard to trace by eyes.

1. It would be good if you can provide the crash logs
2. comment out those external dependancies so we can drop in our project and test it out.

**Comment by chrene** [comment]
I don't think it's a good idea to reload the layout on the background. Try to keep things simple on the main thread and see if you get the same error
