### ISSUE TITLE
UICollectionView sectionheader becomes unsticky after reloadData()

### ISSUE THREAD

**Issue by sumitjain7** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#81]
I added a Parallax header from a XIB and added a section header too. Everything works fine until I call uicollectionView.reloadData().
After calling reloadData(), both parallax header and section header slides up on scrolling.
Please help.

**Comment by jamztang** [comment]
hi @sumitjain7 I recently updated a new version, would you try the latest version fixed your issue? If not please help provide a sample project for us to look at, thanks!

**Comment by sumitjain7** [comment]
Which files should I download?

**Comment by jamztang** [comment]
0.2.8 is the latest version, just clone this project or update on cocoapods
