### ISSUE TITLE
Issue with reloadData and contentOffset

### ISSUE THREAD

**Issue by mberube09** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#87]
I have implemented a CollectionView with a search textfield. In the case I have let say scrolled to the bottom of the collectionview and then I reloadData (with less items in the collection view) then the header stays where it were (in the middle of the section) instead of moving back to the top of the section since with see it completely. 

It is kind of hard to explain but I have uploaded on small sample project wihich explains it all. All you have to do is run the app, scroll to the bottom of the collection view and press to button at the top.

https://drive.google.com/file/d/0B6sI4Feh1HJUb3pGa2pBUmY4QW8/view?usp=sharing

I also posted the question on SO. http://stackoverflow.com/questions/31656903/csstickyheaderflowlayout-header-frame

Thanks

**Comment by jamztang** [comment]
Would the patch suggested in #102 fix for you?

**Comment by mberube09** [comment]
I have tried with the suggested fix but sadly it does not fix

**Comment by jamztang** [comment]
It must be something to do with the Initial and Final attributes methods, but sorry that I haven't get a chance to look at that yet.
