### ISSUE TITLE
Animating parallax view by changing its size

### ISSUE THREAD

**Issue by kevinnguy** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#92]
Is it possible to animate the parallax view's size by changing its `parallaxHeaderReferenceSize`? I'm currently learning more about `UICollectionViewFlowLayout` and would like to see if this was possible. Thanks!

**Comment by jamztang** [comment]
did you try updating the parallaxHeaderReferenceSize inside UIView animation block or UICollectionView performBatchUpdate block?
