### ISSUE TITLE
Error with  pods use_frameworks! 

### ISSUE THREAD

**Issue by mblyk** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#93]
"Definition of 'CSStickyHeaderFlowLayout' must be imported from module 'CSStickyHeaderFlowLayout.CSStickyHeaderFlowLayout' before it is required"
and 
 "duplicate interface definition"
and "Property has a previous declaration"
 after start use pods with use_frameworks!

**Comment by jamztang** [comment]
Not sure about the solution yet

**Comment by mlb5000** [comment]
ya I've started getting this too...did you get anywhere with this @mblyk ?

**Comment by mlb5000** [comment]
Looks like another project had a similar error and managed to fix it somehow: https://github.com/Roobiq/RBQFetchedResultsController/issues/8

**Comment by mlb5000** [comment]
@mblyk Looks like you need to import the headers like this:

    #import <CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayoutAttributes.h>

and not just:

    #import "CSStickyHeaderFlowLayoutAttributes.h"

**Comment by mcmatan** [comment]
@mlb5000 you saved my life. Thank you!

**Comment by fernandolicon** [comment]
Yes, @mlb5000 solutions worked great for me!

**Comment by jamztang** [comment]
Great, thanks for pointing out! @mlb5000

**Comment by AyeChanPyaeSone** [comment]
it works. thanks you. #import <CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout.h>

**Comment by shejis** [comment]
@jamztang In ios 9.0 CSStickyHeaderFlowLayout working fine. But In Ios 10 and more has some bugs. It says 'NSInternalInconsistencyException', reason: 'layout attributes for supplementary item at index path (<NSIndexPath: 0xc000000000000116> {length = 2, path = 1 - 0}) changed from <CSStickyHeaderFlowLayout: 0x12d95eab0> indexPath: {1, 0} zIndex: 1024 valid: YES kind: UICollectionElementKindSectionHeader to <CSStickyHeaderFlowLayout: 0x12d975410> indexPath: {1, 0} zIndex: 1024 valid: YES kind:

**Comment by chrene** [comment]
@shejis see [https://github.com/CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout/issues/144](this)
