### ISSUE TITLE
Self sized header according to the content of it

### ISSUE THREAD

**Issue by Luissoo** [CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout#99]
Hi,

I'm using CSStickyHeaderFlowLayout for my User Profile Header.
In this header i got infomartions of the user or no.

Right now the size of it is hardcoded 
```
let parallaxHeaderReferenceSize: CGFloat = 273.0
```
Anyone knows how to have my header self-sized according to the content of it and not hardcoded 

Thanks !

**Comment by jamztang** [comment]
You have to calculate manually and update the value

**Comment by RJiryes** [comment]
@jamztang  is there no other way? Thanks.

**Comment by chrene** [comment]
I'm afraid not at this point.
